### ISSUE TITLE
Imperfect tabular number figure

### ISSUE THREAD

**Issue by barmadrid** [SorkinType/SplineSans#2]
Hi,

It seems that Gnome Shell by default (Adwaita theme) defaults to Tabular figures. [(More here)](https://gitlab.gnome.org/GNOME/gtk/-/issues/41)
I noticed that using Spline Sans, the number 1 character look is not very good. An example below is from within the Gnome Tweak Tool:
![Screenshot from 2022-04-04 18-23-14](https://user-images.githubusercontent.com/61072940/161853040-f1ec605b-0b51-4a27-82e3-e523b39206e9.png)

Tested with two different high DPI screens.

Thanks in advance!

**Comment by EbenSorkin** [comment]
I am pretty sure I know why and how to fix it. I'll see about getting it into source this evening and having it pushed to published fonts ASAP

**Comment by EbenSorkin** [comment]
I pushed an update fixing this and 50 or so other little things in the source. But no new generated fonts to the repo yet. I may have 1-2 other little things to update and then the fonts will be in the repo. I am not sure how quickly the update will pump into Google fonts.

**Comment by bghryct** [comment]
hey @barmadrid as @EbenSorkin  pointed out you can use the fonts that are generated from the source that he's fixed now, but if you're able to be a little patient we should be pushing all of this to google fonts in the next couple of weeks. Thanks for bringing the interpolation error to our attention, and I hope you're enjoying using the font!

**Comment by barmadrid** [comment]
Thank you @EbenSorkin and @bghryct. I use TTF's, so will definitely be using the re-grenrated files from here instead of waiting for GF!

**Comment by bghryct** [comment]
@barmadrid Happy to help, if you notice anything else please let us know in a new issue. I'm going to close this now considering I think this particular problem is solved. Thanks again for your feedback it helps make the font even better!
